server:
  port: 8082

  error:
    whitelabel:
      enabled: false
      #spring:
      # cloud:
      #  config:
      #      uri: http://localhost:8888

    #logging:
    # level:
    #  ROOT: INFO
    # com.pw: ${LOG_LEVEL_OREO}
spring:
  application:
    name: shop-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/shopdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false #${OREO_REFERRAL_ENGINE_DB_URL}
    username: root #${OREO_REFERRAL_ENGINE_DB_USER_NAME}
    password: #${OREO_REFERRAL_ENGINE_DB_USER_PASS}
  flyway:
    locations: classpath:db.migration
    baseline-on-migrate: true


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB



guru:
   username: wilki
   password: wilki1234





